### ISSUE TITLE
Devices not recognized

### ISSUE THREAD

**Issue by paleiadevelopment** [pzim-devdata/tahoma#2]
Hi! 
after getting everything to work, sadly the application seems to not support the types of device I use.
The prompt said to post about this here, so I am:
EG Erker mitte,io://2026-9407-8819/1402064,PositionableScreen
Device 'EG Erker mitte' NOT controlled by tahoma yet
Balkon,io://2026-9407-8819/2583581,PositionableHorizontalAwning
Device 'Balkon' NOT controlled by tahoma yet

Is there anything else I can provide? I hope support can be added. These are Somfy sunscreens.

**Comment by pzim-devdata** [comment]
Yes you are right, I can add PositionableScreen and PositionableHorizontalAwning. But for now I'm very busy (I have a lot of work). Could you please wait for max one month ? If I had time I will had Somfy sunscreens and let you know. Sorry for the time.

**Comment by pzim-devdata** [comment]
Finally, I will do it now ;-), could try with this two files ?
Replace get_devices_url.py and tahoma.py in the tahoma's folder and let me know :
[Somfy_update.zip](https://github.com/pzim-devdata/tahoma/files/11160585/Somfy_update.zip)

**Comment by paleiadevelopment** [comment]
it works!!! Thank you SO much!

Is it also possible to open/close partway? You can do that in Somfy's official app. Like open 50% for example.
That would be the cherry on top :)  But even "just" opening/closing is already so much nicer than always using the app!

**Comment by pzim-devdata** [comment]
Did you tried 'MY' ?

**Comment by paleiadevelopment** [comment]
Yes, My works, but that puts it to one pre-saved setting. You can't do "My50" for example and programming that "my" state on Somfy's app is horrible, to say the least. Half of the time it saves the wrong setting.

No worries - if you ever feel like building it in, I volunteer for testing :)

**Comment by pzim-devdata** [comment]
I'm happy that it works, I wasn't sure. I will check if I can found an option for opening to xx%, but I'm not very sure, because I have already tried with Velux, which is IO protocol too, and it didn't worked. Send me a message in one month, I will be on holidays and I will try to find something for that. Sorry

**Comment by paleiadevelopment** [comment]
Yes, open, close, stop and my work perfectly fine :)

**Comment by pzim-devdata** [comment]
ok, thank you

**Comment by pzim-devdata** [comment]
For now you can try the sleep function : for exemple :  tahoma close shutter kitchen; sleep 10; tahoma open shutter kitchen; sleep 3; tahoma stop shutter kitchen and create a shortcut with this command called 'close shutter to 75%' for instance.

For configuring the MY command it can be done with the remote control by pressing the MY button for 10 seconds on the position you want to save.

**Comment by pzim-devdata** [comment]
This is an exemple of shortcut : 
[Close screen Erker to 75%.zip](https://github.com/pzim-devdata/tahoma/files/11303096/Close.screen.Erker.to.75.zip)

**Comment by pzim-devdata** [comment]
As promised, the work is done. 
Could you please try the following command and let me know if it works:  `python3 'F:\Portable\tahoma\tahoma.py' 25 PositionableScreen Erker` ?
