### ISSUE TITLE
Add SmartPlug Devices (Sonoff/Ikea/Silvercrest)

### ISSUE THREAD

**Issue by ingelumer** [pzim-devdata/tahoma#6]
Hello, 
May I ask you to add following SmartPlugs from Sonoff, Ikea and Silvercrest to your nice plugin?
They all work fine through Tahoma App.

Here some information from the log:

Sonoff S26R2ZB Smart Plug, ZigBee
> Sonoff SP1 - DB Cams,zigbee://2014-2386-6039/55609/1,StatefulOnOff,OnOff,zigbee:OnOffComponent
> Sonoff SP1 - DB Cams,zigbee://2014-2386-6039/55609/1,StatefulOnOff,OnOff,zigbee:OnOffComponent
> Device 'Sonoff SP1 - DB Cams' NOT controlled by tahoma yet

Ikea TRÅDFRI Smart Plug
> StkD IkTf 1,zigbee://2014-2386-6039/2692/1,StatefulOnOff,OnOff,zigbee:OnOffComponent
> StkD IkTf 1,zigbee://2014-2386-6039/2692/1,StatefulOnOff,OnOff,zigbee:OnOffComponent
> Device 'StkD IkTf 1' NOT controlled by tahoma yet

SilverCrest Smart Plug (Lidl)
>StkD SilCr 3 Flurlampe,zigbee://2014-2386-6039/9064/11,StatefulOnOff,OnOff,zigbee:OnOffComponent
>StkD SilCr 3 Flurlampe,zigbee://2014-2386-6039/9064/11,StatefulOnOff,OnOff,zigbee:OnOffComponent
>Device 'StkD SilCr 3 Flurlampe' NOT controlled by tahoma yet

Many thanks 
Ingelumer

**Comment by pzim-devdata** [comment]
Hello,

I will attempt to add them tomorrow. I’ll provide you with two files: tahoma.py and get_devices.py to replace in your “tahoma” folder. Could you please test to see if everything is working properly?

Additionally, could you provide information on what the Sonoff S26R2ZB Smart Plug, ZigBee, Ikea TRÅDFRI Smart Plug, and SilverCrest Smart Plug (Lidl) are? (Are these plugs?)

And could you tell me if you use the Pypi version or the Github version ?

Thank you.

**Comment by ingelumer** [comment]
thank you so much, works like a charm now :-)

Yes I confirm these devices are plugs, here are the links:

[Sonoff S26R2ZB Smart Plug, ZigBee](https://sonoff.tech/product/smart-plugs/s26r2zb/)

[Ikea TRÅDFRI Smart Plug](https://www.ikea.com/de/de/p/tradfri-steckdose-funkgesteuert-smart-00377314/?openFiche=true&utm_source=google&utm_medium=surfaces&utm_campaign=shopping_feed&utm_content=free_google_shopping_clicks_Lighting_Homeelectronics&gad_source=1&gclid=CjwKCAiA9ourBhAVEiwA3L5RFltQxs-7m6RENjjS1FAr4WxhsXSZpTRei7NFJajaoifq17mht1zUnxoCUo4QAvD_BwE&gclsrc=aw.ds)

[SilverCrest Smart Plug (Lidl)](https://www.lidl.de/p/silvercrest-steckdosen-zwischenstecker-zigbee-smart-home-mit-energiezaehler/p100346911?mktc=shopping_shop&gad_source=1&gclid=CjwKCAiA04arBhAkEiwAuNOsIss9XfISfE6qJJzVvTMN6oV82SbzHiZcp0KA9daOnlFOkvPZwivJ2BoCkqkQAvD_BwE&et_uk=067f4a40d55649ec856527c6991c4127)
