### ISSUE TITLE
Feature Request: Functions to toggle plug and to get device state

### ISSUE THREAD

**Issue by ingelumer** [pzim-devdata/tahoma#7]
Hello,

it be perfectly nice to have a function to toggle a device status, eg a plug (from off to on, or from on to off).

Another helpful function would be just to return the state of a device.

Would this be possible to be implemented?

Many thanks!
Ingelumer

**Comment by pzim-devdata** [comment]
Hello,

I have published a new version:

> it be perfectly nice to have a function to toggle a device status, eg a plug (from off to on, or from on to off).

I have added a `toggle` action for compatible devices

>'Another helpful function would be just to return the state of a device.

Thanks, I have forgot to add the states for StatefulOnOff and StatefulOnOffLight. now you can  use the SENSOR category for IO plugs, spotalarms and lights. For example: `tahoma get sensor [“StkD IkTf 1”]`

All information about this update are listed there: [release_note](https://github.com/pzim-devdata/tahoma/releases/tag/V2.3.4)

Could you tell me if everything works fine ?

Thanks!

**Comment by ingelumer** [comment]
I am impressed by the speed of your implementation times :-)
Many thanks, both functions work well in the new release!
